services:
  pairgoth:
    container_name: pairgoth
    image: eclipse-temurin:21-jre
    working_dir: /home/app/pairgoth
    user: "${APP_UID}:${APP_GID}"
    command: java -jar pairgoth-engine.jar
    volumes:
      - ./pairgoth.properties:/home/app/pairgoth/pairgoth.properties
      - ./data/app:/home/app/pairgoth
    ports:
      - '8080:8080'
    environment:
      HOME: "/home/app"
      USER: "app"
    stdin_open: true
    tty: true
